import type { Preferencias } from "@/types/preferencias";

export const PREFERENCIAS_DEFAULT: Preferencias = {
  version: 1,
  tema: "sistema",
  colorAcento: "amarillo",
  densidad: "comoda",
  altoContraste: false,
  tamanoFuente: "mediano",
  anchoContenido: "fijo",
  sonidos: true,
  haptica: true,
  paletaComandos: true,
  atajosTeclado: true,
  dashboardModulos: [],
  idioma: "es",
  formatoHora: "24",
  zonaHorariaModo: "dispositivo",
  zonaHorariaManual: "America/Santiago",
  notificacionesPush: false,
  notificacionesCategorias: {
    mensajes: true,
    comentarios: true,
    evaluaciones: true,
    visitas: true,
    bitacoras: true,
    documentos: true,
    asignaciones: true,
    alertasAdministrativas: true,
  },
  noMolestar: { activo: false, inicio: "22:00", fin: "07:00" },
  resumenEmail: "desactivado",
  cookies: { tecnicas: true, analisis: true, publicidad: false },
  borradoresAutomaticos: true,
};
